### ISSUE TITLE
multigrid

### ISSUE THREAD

**Issue by mrheld** [feltor-dev/feltor#23]
Multigrid should cancel when the solution is already the input vector

**Comment by mwiesenberger** [comment]
should I look into that or do you?

**Comment by mrheld** [comment]
would be nice

**Comment by mwiesenberger** [comment]
Just went over the problem and I think the most consistent way to solve it is by an if else statement in the src code, since there the initial guess for gamma_n is extrapolated from previous solutions, which is of course not the exact solution. I guess this is why 1 iteration is needed. I tried to insert the check for solution in the multigrid and it did not change anything.

**Comment by mwiesenberger** [comment]
Is this resolved, can we close it?
